/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dados.DAOException;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        leiloesEmAndamento = new javax.swing.JList();
        leilaoAndamento = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        leiloesEncerrados = new javax.swing.JList();
        leilaoEncerrado = new javax.swing.JLabel();
        cadastrarLeilao = new javax.swing.JButton();
        encerrarLeilao = new javax.swing.JButton();
        cadastrarLance = new javax.swing.JButton();
        popularBanco = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaDeUsuario = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        cadastrarUsuario = new javax.swing.JButton();
        atualizarLeiloesAndamento = new javax.swing.JButton();
        atualizarLeiloesEncerrados = new javax.swing.JButton();
        atualizarUsuarios = new javax.swing.JButton();
        verLancesLeilao = new javax.swing.JButton();
        verBens = new javax.swing.JButton();
        verLancesUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(leiloesEmAndamento);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 670, 220));

        leilaoAndamento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        leilaoAndamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leilaoAndamento.setText("Leilões em andamento");
        getContentPane().add(leilaoAndamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 440, -1));

        jScrollPane2.setViewportView(leiloesEncerrados);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 670, 220));

        leilaoEncerrado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        leilaoEncerrado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leilaoEncerrado.setText("Leilões encerrados");
        getContentPane().add(leilaoEncerrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 430, -1));

        cadastrarLeilao.setText("Cadastrar Leilão");
        cadastrarLeilao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarLeilaoActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarLeilao, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 120, 40));

        encerrarLeilao.setText("Encerrar Leilão");
        encerrarLeilao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encerrarLeilaoActionPerformed(evt);
            }
        });
        getContentPane().add(encerrarLeilao, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 120, 40));

        cadastrarLance.setText("Dar Lance");
        cadastrarLance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarLanceActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarLance, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 300, 120, 40));

        popularBanco.setText("Popular Banco de Dados");
        popularBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popularBancoActionPerformed(evt);
            }
        });
        getContentPane().add(popularBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 490, 180, 80));

        jScrollPane3.setViewportView(listaDeUsuario);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, 610, 220));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lista de Usuários");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 420, -1));

        cadastrarUsuario.setText("Cadastrar Usuário");
        cadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, -1, 40));

        atualizarLeiloesAndamento.setText("Atualizar");
        atualizarLeiloesAndamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarLeiloesAndamentoActionPerformed(evt);
            }
        });
        getContentPane().add(atualizarLeiloesAndamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, -1, -1));

        atualizarLeiloesEncerrados.setText("Atualizar");
        atualizarLeiloesEncerrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarLeiloesEncerradosActionPerformed(evt);
            }
        });
        getContentPane().add(atualizarLeiloesEncerrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 640, -1, -1));

        atualizarUsuarios.setText("Atualizar");
        atualizarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(atualizarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 300, -1, -1));

        verLancesLeilao.setText("Ver Lances");
        verLancesLeilao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verLancesLeilaoActionPerformed(evt);
            }
        });
        getContentPane().add(verLancesLeilao, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 110, 40));

        verBens.setText("Ver Bens");
        verBens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verBensActionPerformed(evt);
            }
        });
        getContentPane().add(verBens, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 110, 40));

        verLancesUsuario.setText("Ver Lances");
        verLancesUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verLancesUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(verLancesUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 300, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarLeilaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarLeilaoActionPerformed
        new TelaLeiloes().setVisible(true);
    }//GEN-LAST:event_cadastrarLeilaoActionPerformed

    private void popularBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popularBancoActionPerformed
        try {
            ImportarSQL.execute("ScriptsBanco.txt");
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        CadastroLeilaoController leilaoController;
        CadastroUsuarioController usuarioController;
        try {
            leilaoController = new CadastroLeilaoController();
            ListaLeilaoModel leilaoAtivosModel = new ListaLeilaoModel(leilaoController.getAtivos());
            leiloesEmAndamento.setModel(leilaoAtivosModel);
            ListaLeilaoModel leilaoEncerradosModel = new ListaLeilaoModel(leilaoController.getEncerrados());
            leiloesEncerrados.setModel(leilaoEncerradosModel);
            usuarioController = new CadastroUsuarioController();
            ListaUsuariosModel usuariosModel = new ListaUsuariosModel(usuarioController.getTodos());
            listaDeUsuario.setModel(usuariosModel);
        } catch (DAOException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_popularBancoActionPerformed

    private void cadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarUsuarioActionPerformed
        new TelaUsuarios().setVisible(true);
    }//GEN-LAST:event_cadastrarUsuarioActionPerformed

    private void atualizarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarUsuariosActionPerformed
        CadastroUsuarioController usuarioController;
        try {
            usuarioController = new CadastroUsuarioController();
            ListaUsuariosModel usuariosModel = new ListaUsuariosModel(usuarioController.getTodos());
            listaDeUsuario.setModel(usuariosModel);
        } catch (DAOException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_atualizarUsuariosActionPerformed

    private void atualizarLeiloesAndamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarLeiloesAndamentoActionPerformed
        CadastroLeilaoController leilaoController;
        try {
            leilaoController = new CadastroLeilaoController();
            ListaLeilaoModel leilaoModel = new ListaLeilaoModel(leilaoController.getAtivos());
            leiloesEmAndamento.setModel(leilaoModel);
        } catch (DAOException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_atualizarLeiloesAndamentoActionPerformed

    private void atualizarLeiloesEncerradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarLeiloesEncerradosActionPerformed
        CadastroLeilaoController leilaoController;
        try {
            leilaoController = new CadastroLeilaoController();
            ListaLeilaoModel leilaoModel = new ListaLeilaoModel(leilaoController.getEncerrados());
            leiloesEncerrados.setModel(leilaoModel);
        } catch (DAOException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_atualizarLeiloesEncerradosActionPerformed

    private void encerrarLeilaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encerrarLeilaoActionPerformed
        if (leiloesEmAndamento.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione um leilão!");
        } else {
            int index = leiloesEmAndamento.getSelectedIndex();
            ListaLeilaoModel model = (ListaLeilaoModel) leiloesEmAndamento.getModel();
            int leilaoId = model.getElementAt(index).getLeilaoId();
            CadastroLeilaoController leilaoController;
            try {
                leilaoController = new CadastroLeilaoController();
                leilaoController.encerrarLeilao(leilaoId);
            } catch (DAOException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_encerrarLeilaoActionPerformed

    private void cadastrarLanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarLanceActionPerformed
        if (leiloesEmAndamento.isSelectionEmpty() || listaDeUsuario.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione um leilão e um usuário!");
        } else {
            CadastroLanceController lanceController;
            int leilaoIndex = leiloesEmAndamento.getSelectedIndex();
            ListaLeilaoModel leilaoModel = (ListaLeilaoModel) leiloesEmAndamento.getModel();
            int leilaoId = leilaoModel.getElementAt(leilaoIndex).getLeilaoId();
            int usuarioIndex = listaDeUsuario.getSelectedIndex();
            ListaUsuariosModel usuariosModel = (ListaUsuariosModel) listaDeUsuario.getModel();
            String usuarioId = usuariosModel.getCpfOuCnpjSelecionado(usuarioIndex);
            double valor = Double.parseDouble(
                    JOptionPane.showInputDialog(this, "Informe o valor do lance:"));
            try {
                lanceController = new CadastroLanceController();
                lanceController.adicionar(leilaoId, usuarioId, valor);
            } catch (DAOException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cadastrarLanceActionPerformed

    private void verLancesLeilaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verLancesLeilaoActionPerformed
        if (leiloesEmAndamento.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione um leilão!");
        } else {
            int index = leiloesEmAndamento.getSelectedIndex();
            ListaLeilaoModel leilaoModel = (ListaLeilaoModel) leiloesEmAndamento.getModel();
            int leilaoId = leilaoModel.getElementAt(index).getLeilaoId();
            TelaLancesLeilao telaLancesLeilao = new TelaLancesLeilao();
            try {
                CadastroLanceController lanceController = new CadastroLanceController();
                ListaLanceModel lanceModel = new ListaLanceModel(lanceController.getLancesPorLeilaoID(leilaoId));
                telaLancesLeilao.listaLancesLeilao.setModel(lanceModel);
                telaLancesLeilao.setVisible(true);
            } catch (DAOException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_verLancesLeilaoActionPerformed

    private void verBensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verBensActionPerformed
        if (leiloesEmAndamento.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione um leilão!");
        } else {
            int index = leiloesEmAndamento.getSelectedIndex();
            ListaLeilaoModel leilaoModel = (ListaLeilaoModel) leiloesEmAndamento.getModel();
            int leilaoId = leilaoModel.getElementAt(index).getLeilaoId();
            try {
                CadastroBemController bemController = new CadastroBemController();
                System.out.println(bemController.getBensPorLoteId(leilaoId));
                ListaBemModel bemModel = new ListaBemModel(bemController.getBensPorLoteId(leilaoId));
                TelaBensLeilao telaBensLeilao = new TelaBensLeilao();
                telaBensLeilao.listaBensLeilao.setModel(bemModel);
                telaBensLeilao.setVisible(true);
            } catch (DAOException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_verBensActionPerformed

    private void verLancesUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verLancesUsuarioActionPerformed
        if (listaDeUsuario.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione um usuário!");
        } else {
            int index = listaDeUsuario.getSelectedIndex();
            ListaUsuariosModel usuariosModel = (ListaUsuariosModel) listaDeUsuario.getModel();
            String usuarioId = usuariosModel.getCpfOuCnpjSelecionado(index);
            CadastroLanceController lanceController;
            try {
                lanceController = new CadastroLanceController();
                ListaLanceModel lanceModel = new ListaLanceModel(lanceController.getLancesPorUsuarioID(usuarioId));
                TelaLancesUsuario telaLancesUsuario = new TelaLancesUsuario();
                telaLancesUsuario.listaLancesUsuario.setModel(lanceModel);
                telaLancesUsuario.setVisible(true);
            } catch (DAOException ex) {
                Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_verLancesUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarLeiloesAndamento;
    private javax.swing.JButton atualizarLeiloesEncerrados;
    private javax.swing.JButton atualizarUsuarios;
    private javax.swing.JButton cadastrarLance;
    private javax.swing.JButton cadastrarLeilao;
    private javax.swing.JButton cadastrarUsuario;
    private javax.swing.JButton encerrarLeilao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel leilaoAndamento;
    private javax.swing.JLabel leilaoEncerrado;
    private javax.swing.JList leiloesEmAndamento;
    private javax.swing.JList leiloesEncerrados;
    private javax.swing.JList listaDeUsuario;
    private javax.swing.JButton popularBanco;
    private javax.swing.JButton verBens;
    private javax.swing.JButton verLancesLeilao;
    private javax.swing.JButton verLancesUsuario;
    // End of variables declaration//GEN-END:variables
}
