/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dados.DAOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import negocio.Bem;

/**
 *
 * @author Lucas
 */
public class TelaLeiloes extends javax.swing.JFrame {

    /**
     * Creates new form TelaUsuario
     */
    public TelaLeiloes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataInicioLabel = new javax.swing.JLabel();
        dataInicioTextField = new javax.swing.JTextField();
        dataFimLabel = new javax.swing.JLabel();
        dataFimTextField = new javax.swing.JTextField();
        tipoLabel = new javax.swing.JLabel();
        tipoTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cadastrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        valorDoLote = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        descricao_bemTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        detalhes_bemTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        categoria_bemTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaDeBens = new javax.swing.JList();
        AdicionarBem = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tipoLanceTextField = new javax.swing.JTextField();
        CadastrarLote = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dataInicioLabel.setText("Data Inicio");
        getContentPane().add(dataInicioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));
        getContentPane().add(dataInicioTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 90, -1));

        dataFimLabel.setText("Data Fim");
        getContentPane().add(dataFimLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));
        getContentPane().add(dataFimTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 90, -1));

        tipoLabel.setText("Tipo");
        getContentPane().add(tipoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));
        getContentPane().add(tipoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 153, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Leilões");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 538, -1));

        cadastrar.setText("Cadastrar Leilão");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 640, 190, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastrar Lote");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 540, -1));

        jLabel3.setText("Valor do Lote");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));
        getContentPane().add(valorDoLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 170, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Inserir Bens");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        jLabel5.setText("Descrição");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));
        getContentPane().add(descricao_bemTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 190, -1));

        jLabel6.setText("Detalhes");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));
        getContentPane().add(detalhes_bemTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 340, -1));

        jLabel7.setText("Categoria");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));
        getContentPane().add(categoria_bemTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 200, -1));

        jScrollPane1.setViewportView(listaDeBens);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 630, 170));

        AdicionarBem.setText("Adicionar Bem");
        AdicionarBem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarBemActionPerformed(evt);
            }
        });
        getContentPane().add(AdicionarBem, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, -1, -1));

        jLabel8.setText("Tipo Lance");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, -1, -1));
        getContentPane().add(tipoLanceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 140, -1));

        CadastrarLote.setText("Criar Lote");
        CadastrarLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarLoteActionPerformed(evt);
            }
        });
        getContentPane().add(CadastrarLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        String tipo = tipoTextField.getText();
        String dataInicio = dataInicioTextField.getText();
        String dataFim = dataFimTextField.getText();
        String tipoLance = tipoLanceTextField.getText();
        try {
            CadastroLeilaoController leilaoController = new CadastroLeilaoController();
            leilaoController.adicionar(loteId, 0.0, "", tipo, tipoLance, dataInicio, dataFim);
        } catch (DAOException ex) {
            Logger.getLogger(TelaLeiloes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(TelaLeiloes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_cadastrarActionPerformed

    private void AdicionarBemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarBemActionPerformed
        String descricao = descricao_bemTextField.getText();
        String detalhes = detalhes_bemTextField.getText();
        String categoria = categoria_bemTextField.getText();
        try {
            CadastroBemController bemController = new CadastroBemController();
            Bem bem = bemController.adicionarBem(loteId, descricao, detalhes, categoria);            
            model.addElement(bem.toString());
            listaDeBens.setModel(model);
        } catch (DAOException ex) {
            Logger.getLogger(TelaLeiloes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_AdicionarBemActionPerformed

    private void CadastrarLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarLoteActionPerformed
        Double valor = Double.parseDouble(valorDoLote.getText());
        try {
            CadastroLoteController loteController = new CadastroLoteController();
            boolean adicionado = loteController.adicionarLote(valor);
            if(adicionado) {
                loteId = loteController.getUltimoLoteId();                
            }            
        } catch (DAOException ex) {
            Logger.getLogger(TelaLeiloes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CadastrarLoteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicionarBem;
    private javax.swing.JButton CadastrarLote;
    private javax.swing.JButton cadastrar;
    private javax.swing.JTextField categoria_bemTextField;
    private javax.swing.JLabel dataFimLabel;
    private javax.swing.JTextField dataFimTextField;
    private javax.swing.JLabel dataInicioLabel;
    private javax.swing.JTextField dataInicioTextField;
    private javax.swing.JTextField descricao_bemTextField;
    private javax.swing.JTextField detalhes_bemTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listaDeBens;
    private javax.swing.JLabel tipoLabel;
    private javax.swing.JTextField tipoLanceTextField;
    private javax.swing.JTextField tipoTextField;
    private javax.swing.JTextField valorDoLote;
    // End of variables declaration//GEN-END:variables
    private int loteId;
    private DefaultListModel model = new DefaultListModel();
}
